adityaarakeri/Interview-solved

Company/string_manipulation.py
Write a function that changes every second word in a sentence to "Hello"
Example 
**Input sentence** 
Hey I love going to the park 
**output sentence** 
Hey Hello love Hello to Hello park
=> string_manipulation

Company/unique_username.py
Unique usernames
You get an list of names and need to return a list of unique usernames.
For a duplicate name, add the next integer after the name
For example:
Input
['Julie', 'Emma', 'Zoe', 'Liam', 'Emma']
Output
['Julie', 'Emma', 'Zoe', 'Liam', 'Emma1']
Input
['Julie', 'Zoe', 'Zoe', 'Liam', 'Emma', 'Zoe']
Output
['Julie', 'Zoe', 'Zoe1', 'Liam', 'Emma', 'Zoe2']
=> Unique usernames

Company/hash_runners.py
starting to work on #2 :sparkles:
=> [Hacktoberfest 2019] Added a hash problem

CodeWars/ArrayPlusArray.py, test/test_array_plus_array.py
Array Plus Array in Code Wars
test file included in the test folder
:)
=> Array Plus Array in Code Wars plus test file

Company/fibonacci.py, test/test_fibonacci.py
interview question but can also be found on [leetcode ](https://leetcode.com/problems/fibonacci-number/):
The Fibonacci numbers, commonly denoted F(n) form a sequence, called the Fibonacci sequence, 
such that each number is the sum of the two preceding ones, starting from 0 and 1. 
F(0) = 0,   F(1) = 1
F(N) = F(N - 1) + F(N - 2), for N > 1.
Given N (N-th number in fibonacci sequence), calculate F(N).
Input: 6
Output: 8
Explanation: 
- F(6) = 0, 1, 1, 2, 3, 5, 8
- F(6) = F(5) + F(4) = 5 + 3 = 8.
=> added fibonacci sequence problem 

LeetCode/two_sum_II.py, test/test_two_sum_II.py
Added LeetCode 167 two_sum_II.py
=> Added LeetCode 167 two_sum_II.py

Company/vowel_count.py, test/test_vowel_count.py
You get a string and need to return its number of vowels.
For this test, we will only consider a, e, i, o and u as vowels.
For example:
Input: "Alabama"
Output: 4
Input: "Caserta"
Output: 3
=> Vowel Count

Important/kth_smallest_element.py
You are given an array of integers, and you have to find the k-th smallest number in the array.
**Input Format**
The first line contains the value of K
The second line contains a space separated list of integers
**Output Format**
The only line contains the k-th smallest number in the array
Example:
**Input**
3
7 10 4 3 20 15
**Output**
7
=> added finding kth smallest element in an array algorithm

GeeksforGeeks/recursion_all_indices.py, test/test_recursion_all_indices.py
Given an array of distinct integers with size N and an integer X 
Display all the indices of the integer X in the array using RECURSION only
If no X occurs in the array no output should be displayed
=> Using recursion to display all indices of an integer in an array

LeetCode/5.py
Not the best in runtime, but simple to read
=> Simple solution for leetCode palindrome task

LeetCode/sum_root_to_leaf_numbers.py, test/test_sum_root_to_leaf_numbers.py
@adityaarakeri Please accept this PR :)
=> Added LeetCode 129. Sum Root to Leaf Numbers

CodeWars/First_non_repeating_character.py
Hi, I added a CodeWars solution. I am doing this in the spirit of Hacktoberfest to learn about open source projects. Cheers!
=> Add CodeWars solution

Company/matrixOperations.py, Important/contiguous_highest_sum.py, test/test_array_plus_array.py, test/test_contiguous_highest_sum.py, test/test_fibonacci.py, test/test_matrix_operation.py, test/test_string_fill.py
- new sliding window algo
- tests for contiguous sum
- updates
=> contiguous sum plus updates

LeetCode/21.py, LeetCode/28.py
Added solution and demo to leetcode question
=> Added solution to leetcode #21

LeetCode/217.py
Add a solution class and 3 test cases for Leetcode 217, "Contains Duplicate"
=> Add solution to Leetcode 217

Trees and Graphs/AVL Tree.py, Trees and Graphs/Depth-First-Search.py, Trees and Graphs/Djikistra.py, Trees and Graphs/Red Black Tree.py, Trees and Graphs/kruskall.py
Djikistra, Kruskall, Red Black Tree etc.
=> Add solved problems with graphs and trees

CodeWars/battleship-field-validator.py
Delete battleship-field-validator.py
create battleship-field-validator.py
=> squash-battleship-field-validator.py

Company/find_odd_in_constant_space.py, test/test_find_odd_in_constant_space.py
=> #84 - finding odd occurrence with constant space limitation

LeetCode/200.py
**IMPORTANT: Please do not create a Pull Request without an issue.**
**Closing issues**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Add leetcode 200

LeetCode/61.py
**IMPORTANT: Please do not create a Pull Request without an issue.**
**Closing issues**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Add leetcode 61

Important/CalculatePi.py, test/test_CalculatePi.py
This is an interesting and famous interview question. Estimate pi given a random number generator.
=> Added a "calculate pi" interview question

LeetCode/94.py
=> Add leetcode 94

GeeksforGeeks/kadanes_algorithm.py, GeeksforGeeks/lenth_of_longest_contegeous_elements.py
Added .py file for implementation of Kadane's algorithm #58
=>  GeeksforGeeks interview guide : adding Kadane's algorithm #58

CodeWars/Tortoise_Racing.py
#58 
Question with answer code.
Hi! Please merge these files.
=> Added Tortoise_Racing.py

CodeWars/Unique_number.py
#58 
Added interview solved question with solution
=> Added unique number problem

LeetCode/jump_game.py, test/test_jump_game.py
This is the solution of Leetcode question no.55 in python.
=> Add Leetcode Solution

CodeWars/ShortestWord.py
**IMPORTANT: Please do not create a Pull Request without an issue.**
**Closing issues**
Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
=> Added ShortestWord.py into CodeWars

LeetCode/top_k_frequent.py, test/test_top_frequent.py
It contains the solution of the LeetCode Question no.347.<br>
I have also added the test under the tests folder.
Fixes #58
=> Add LeetCode Solution 

HackerRank/Birthday_chocolate.py
Added Hackerrank solution in hacker rank folder
=> Added hackerrank solution

GeeksforGeeks/Tower_of_Hanoi.py
#58 Added code of Tower of Hanoi😊
=> Added code for tower of Hanoi in GeeksforGeeks

LeetCode/100.py
=> Added solution of LeetCode #100

GeeksforGeeks/longest_palindromic_substr.py, GeeksforGeeks/pythagorean_triplet.py, GeeksforGeeks/roman_to_integer.py
=> GeeksForGeeks Interview Guide: Adding python program to find longest palindromic substring in given strings
